name: riverpod_crud_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  bottom_picker: ^2.3.3
  cached_network_image: ^3.3.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  dio_smart_retry: ^6.0.0
  duration: ^3.0.13
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  form_builder_image_picker: ^4.0.0
  form_builder_phone_field: ^2.0.1
  form_builder_validators: ^9.1.0
  gap: ^3.0.1
  hive_flutter: ^1.1.0
  hydrated_state_notifier: ^1.0.0
  hydrated_state_notifier_hive: ^1.0.0
  multiple_result: ^5.1.0
  path_provider: ^2.1.2
  responsive_framework: ^1.1.1
  talker: ^3.2.0
  talker_dio_logger: ^2.4.0
  velocity_x: ^4.1.2

dev_dependencies:
  auto_route_generator: null
  build_runner: null
  custom_lint: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: null

flutter:
  generate: true
  uses-material-design: true
