name: riverpod_crud_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-219.0.dev <4.0.0'

dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_riverpod: ^2.4.9
  form_builder_validators: ^9.1.0
  gap: ^3.0.1
  hive_flutter: ^1.1.0
  multiple_result: ^5.1.0
  responsive_framework: ^1.1.1
  talker: ^3.2.0
  talker_dio_logger: ^2.4.0
  velocity_x: ^4.1.2

dev_dependencies:
  auto_route_generator: null
  build_runner: null
  custom_lint: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: null

flutter:

  uses-material-design: true
